### ISSUE TITLE
build Camera_Server_M5stack error ，lack some function

### ISSUE THREAD

**Issue by hlleng** [STKsettakan/ESPinoCameraV2#1]
![image](https://user-images.githubusercontent.com/4686802/48708214-e771fc00-ec3c-11e8-8ee7-e21f0544bdd2.png)

lack some function

![image](https://user-images.githubusercontent.com/4686802/48708288-24d68980-ec3d-11e8-8c10-e1605582153a.png)

**Comment by STKsettakan** [comment]
please update example file
Thank you
