### ISSUE TITLE
Pins for M5stack Camera

### ISSUE THREAD

**Issue by alhinai21** [STKsettakan/ESPinoCameraV2#2]
in order for [M5Stack Camera esp32 board](https://www.amazon.com/M5Stack-Camera-Antenna-Arduino-Raspberry/dp/B07DVD4J7N/) to work pin numbers should be changed as follow:

```
#define   CONFIG_D0     17
#define   CONFIG_D1     35
#define   CONFIG_D2     34
#define   CONFIG_D3     5
#define   CONFIG_D4     39
#define   CONFIG_D5     18
#define   CONFIG_D6     36
#define   CONFIG_D7     19
#define   CONFIG_XCLK   27
#define   CONFIG_PCLK   21
#define   CONFIG_VSYNC  22
#define   CONFIG_HREF   26
#define   CONFIG_SDA    25
#define   CONFIG_SCL    23 
#define   CONFIG_RESET  15
```

tested and worked, if you want to make this lib for more than one board I suggest to write a variable to let user choose a board and save all pin configs under each board.

thank you for writing this code you save me alot of work.

Regards

**Comment by STKsettakan** [comment]
Thank you for information :)

**Comment by dontsovcmc** [comment]
Thanks!
